Switch from camel case to snake case
SubstraFoundation/substra pull request #222
Opened 2020-09-09 16:15 UTC by Kelvin-M

The backend responses should be more consistent. The goal of this PR is to make sure that all inputs fields and response fields of backend endpoints are in snake_case format.

PRs:

2020-09-09 16:18 UTC, natct10 commented
:snake:

2020-09-10 06:40 UTC, jmorel requested changes

2020-09-10 06:40 UTC, jmorel commented on tests/datastore.py
>      "outModel": None,
There are inModels, outModel and outTrunk/HeadModels in this file, It doesn't have much impact but still :)

2020-09-10 13:07 UTC, Esadruhn approved these changes

2020-09-11 09:33 UTC, jmorel approved these changes

2020-09-14 08:46 UTC, inalgnu approved these changes

2020-09-14 11:41 UTC, merged