Release 0.8.1
SubstraFoundation/substra pull request #264
Opened 2021-04-14 08:32 UTC by Esadruhn

# Changelog

## Features

- Export model and node info
- Debug mode: in a multi node setup, create one local compute plan folder per node
- Debug mode: move the chainkeys to the `local-worker` directory

## Fixes

- client.update_compute_plan: fix when giving a `substra.sdk.schemas.UpdateComputePlanSpec` as input
- Path the order of the `y_pred` and `y_true` in the objective

2021-04-14 08:54 UTC, Kelvin-M submitted a review, later dismissed

2021-04-14 13:15 UTC, AurelienGasser approved these changes
lgtm

2021-04-19 06:56 UTC, samlesu approved these changes

2021-04-19 07:10 UTC, samlesu requested changes
As said on slack, maybe bump of minor as new features are released.

2021-04-19 16:08 UTC, inalgnu approved these changes

2021-04-20 09:51 UTC, samlesu approved these changes
LGTM

2021-04-20 09:52 UTC, merged